apiVersion: v1
kind: Service
metadata:
  name: kube-config-poc-service
  labels:
    app: kube-config-poc
    tier: backend
    role: master
spec:
  type: NodePort
  ports:
  - port: 9092
    targetPort: 8080
  selector:
    app: kube-config-poc
    tier: backend
    role: master