apiVersion: v1
kind: Service
metadata:
  name: kube-config-poc-service
  labels:
    app: kube-config-poc
    tier: backend
    role: master
spec:
  type: NodePort
  ports:
  - port: 9092
    targetPort: 8080
  selector:
    app: kube-config-poc
    tier: backend
    role: master
    
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: kube-config-poc
spec:
  selector:
    matchLabels:
      app: kube-config-poc
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-config-poc
        role: master
        tier: backend
    spec:
      containers:
      - name: kube-config-poc
        image: vimalrkp/kube-config-poc:V1
        env:
         - name: JAVA_OPTIONS
           value: "-Dspring.profiles.active=${ENVIRONMENT}"
         - name: SPRING_PROFILES_ACTIVE
           value: prod-region1
        envFrom:
          - configMapRef:
            name: application-prod-region1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080